### ISSUE TITLE
这个比官方给的好用不少，但是有一个问题并不是所有的表都会创建一个叫做id的，报错

### ISSUE THREAD

**Issue by fengxueguang** [leeprince/gormstruct#1]
<img width="949" alt="image" src="https://github.com/leeprince/gormstruct/assets/7464025/3b35716e-0294-45fe-856d-4134f5777a47">

**Comment by leeprince** [comment]
感谢你的关注，这里有这个问题。设计的想法是，默认所有的主键都是id，并且强烈建议所有的表都有一个自增 ID。既然有这个需求，后面我做一个更新，也欢迎你一起参与提交我做个合并。

**Comment by fengxueguang** [comment]
我们的业务也会有自增id，但是不是叫id这个名字有的是id有的是比如，user_id

**Comment by leeprince** [comment]
明白你的意思，该问题解决了，你可以重新拉下来重新生成，与之前版本的兼容
