### ISSUE TITLE
像这种表的注释有换行符还有字段注释有换行符都会报错

### ISSUE THREAD

**Issue by fengxueguang** [leeprince/gormstruct#2]
CREATE TABLE `q_list` (
  `drillmster_contract_cancel_id` int(11) NOT NULL AUTO_INCREMENT,
 `audit_status` tinyint(4) DEFAULT '0' COMMENT '审核状态 ；0 待审核；\r\n1 通过 2 驳回',
  PRIMARY KEY (`drillmster_contract_cancel_id`)
) ENGINE=InnoDB AUTO_INCREMENT=434 DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC COMMENT='练排班合同解约记录表\r\n（违约记录表）';

当然这和自己明明不规范也有一定关系，但是为了系统健壮性还是要改改

**Comment by leeprince** [comment]
是的，这是一个bug，我已验证：开始在navicat中手动添加\r、\n、\r\n 时，发现navicat 能正常转义这些字符吗，但是如果在navicat 中直接换行，是不会触发自动添加转义符的，则会出现生成错误。
很高兴看到你提交的修改记录，我现在会一一验证，并做好合并和记录。

**Comment by leeprince** [comment]
发现提交的 `merge pull request` 遗漏了表换行的修复（可能后面其他我未审核和校验的代码中包含这部分）
所以在合并了代码之后，我稍微做了修改，用于保留原始的换行符，并且修复了表注释中包含换行的问题
func (m *mysqlModel) lineBreakToBlank(str string) string {
	s := strings.ReplaceAll(str, "\r", "\\r")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r\n", "\\r\\n")
	return s
}

目前该方法解决用于表注释和字段注释中包含换行问题
