### ISSUE TITLE
这种索引中名字有空格，或者索引名字有“，”生成也会有问题

### ISSUE THREAD

**Issue by fengxueguang** [leeprince/gormstruct#3]
CREATE TABLE `vipcard` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `vip_id` int(11) DEFAULT '0' COMMENT 'vip id',
  `v2_type_id` int(11) NOT NULL DEFAULT '0' COMMENT '类型id',
  `is_public_sale` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0 非公开售卖 1公开售卖',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_v2_type_id` (`v2_type_id`),
  KEY `q_vip id` (`vip_id`)
) ENGINE=InnoDB AUTO_INCREMENT=164 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

**Comment by leeprince** [comment]
索引名称中包含空格确实是不规范的。
包括，我适用你提供的SQL去创建表，都是有语法错误的。后来我是将`q_vip id`用下划线连接起来后，在navicat中手动修改，才能复现这个问题。
本来也不打算支持，会保持目前处理逻辑，不过生成的DAO层方法会出现不可用，如果不能直接报错那生成的DAO层不可用，不是我想要的。
同时也看到你提交了修复代码，检查了一下，修复的方式应该能避免报错，不过位置我觉得不太合适。
我现在在生成构建方法的时候，把空格转为下划线了，代码你可以重新拉取下。
```
// 构建方法
func buildFList(list *[]FList, tableStructName string, key ColumnsKey, keyName string, tp string, columnName string) {
	...
	// 还未添加过,则添加
	keyName = strings.ReplaceAll(keyName, " ", "_")
```
