### ISSUE TITLE
这种的报错方法重复

### ISSUE THREAD

**Issue by fengxueguang** [leeprince/gormstruct#4]
CREATE TABLE `q_admin_user` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `is_show` tinyint(1) DEFAULT '1' COMMENT '1显示 2隐藏',
  `is_all` tinyint(1) DEFAULT '1' COMMENT '销售主管是否可以看全部',
  `is_forbid` tinyint(1) DEFAULT '0',
  `qq_band` tinyint(1) DEFAULT '0' COMMENT '1',
  `roleid` int(11) DEFAULT NULL COMMENT '角色，默认岗位id',
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '用户名',
  `realname` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `nickname` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '昵称',
  `password` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `phone` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '手机',
  `sex` tinyint(1) DEFAULT NULL COMMENT '1,男，2，女',
  `birthday` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '生日',
  `email` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '电子邮件',
  `addtime` int(11) DEFAULT NULL COMMENT '加入时间',
  `from` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '来源',
  `from_type` tinyint(4) DEFAULT '0' COMMENT '1 - 导入；2 - 招募;',
  `drillmaster_type` tinyint(4) DEFAULT '0' COMMENT '1 正式教官;2 预备教官；3 潜在教官',
  `openid` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '用户的营中小程序openid',
  `hiredate` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '入职时间',
  `jopnum` int(11) DEFAULT '0' COMMENT '员工的工号',
  `department` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '部门的名称',
  `times` int(11) DEFAULT '6' COMMENT '次数',
  `parent_uid` int(11) DEFAULT '0' COMMENT '关联主管uid',
  `headImg` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '营长头像',
  `bgImg` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '营长背景图片',
  `introduce` longtext CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '营长介绍',
  `wx_number` char(30) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '微信号',
  `wx_qrcode` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '微信二维码',
  `logo` varchar(150) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '渠道商logo',
  `qd_phone` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '渠道联系方式',
  `parent_uids` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '角色父级id串',
  `qd_bli` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '渠道商返佣比例',
  `qduid` int(11) DEFAULT '0' COMMENT '所属渠道商（该用户是二级渠道商的时候才有）',
  `money` decimal(10,2) DEFAULT '0.00' COMMENT '可提现金额',
  `ice_money` decimal(10,2) DEFAULT '0.00' COMMENT '冻结金额',
  `fymoney` decimal(10,2) DEFAULT '0.00' COMMENT '累计返佣',
  `type` tinyint(1) DEFAULT '1' COMMENT '分销规则1当次有效2长期有效',
  `fx_time` int(11) DEFAULT '0' COMMENT '分销有效截止时间',
  `top_status` tinyint(1) DEFAULT '0',
  `update_time` int(11) DEFAULT '0',
  `login_status` tinyint(1) DEFAULT '0' COMMENT '登陆是否需要修改密码',
  `fx_gid` int(11) DEFAULT '0' COMMENT '分销组id',
  `pfxy` int(11) DEFAULT '0' COMMENT '上级分销员',
  `remark` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '分销员备注',
  `kol_fxrule` tinyint(1) DEFAULT '2' COMMENT '当次有效 1  2长期有效',
  `koldata_limit` int(11) DEFAULT '0' COMMENT '有效期  kol_fxrule=2',
  `kol_day` int(11) DEFAULT '0' COMMENT '分销限制天数',
  `area_id` int(11) DEFAULT '0' COMMENT '区域id',
  `ds_type_id` int(11) DEFAULT '0' COMMENT '导师类别id',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态1是正常 2 冻结  3 删除',
  `tag` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '打标签',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '分组id串',
  `nation` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '国籍',
  `idcard` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '证件号',
  `card_type` tinyint(4) DEFAULT '0' COMMENT '1 中国大陆；2中国香港；3中国澳门；4中国台湾；5 外籍；',
  `is_jianzhi` tinyint(1) DEFAULT '0' COMMENT '是否是兼职1是',
  `cb_role_id` tinyint(1) DEFAULT '0' COMMENT '成本端管理员角色',
  `cb_time` int(11) DEFAULT '0' COMMENT '成本端同步时间',
  `fxyq_on` tinyint(1) DEFAULT '1' COMMENT '分销邀请开关2是开启1是禁止',
  `sc_time` int(11) DEFAULT '0',
  `is_hb` int(11) DEFAULT '0' COMMENT '通过分享海报流量的数',
  `is_hb_buy` int(11) DEFAULT '0' COMMENT '通过海报扫码购买的数量',
  `personal_labels` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT '' COMMENT '个人标签',
  `channel_gid` int(11) DEFAULT '0',
  `channel_status` tinyint(1) DEFAULT '1' COMMENT '1 启用，2禁止用',
  `is_can_fx` tinyint(1) DEFAULT '0',
  `ymce_type` tinyint(1) DEFAULT '1',
  `car_team_id` int(11) DEFAULT '0' COMMENT '车队id',
  `nationality` tinyint(1) DEFAULT '0' COMMENT '0 - 中籍；1 - 外籍;',
  `jianzhi_level_code` tinyint(1) DEFAULT '0',
  `store_id` int(11) DEFAULT '1',
  `other_type` tinyint(1) DEFAULT '0' COMMENT '其他平台类型  1小红书  2抖音',
  `kol_type` int(11) NOT NULL DEFAULT '1' COMMENT '1渠道，2学校',
  `fx_gids` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '管理员分销组ID 多个逗号拼接 1,2,2',
  PRIMARY KEY (`uid`),
  KEY `other_type_index` (`other_type`)
) ENGINE=InnoDB AUTO_INCREMENT=2749 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

**Comment by fengxueguang** [comment]
![image](https://github.com/leeprince/gormstruct/assets/7464025/e7706658-b9bf-4243-8805-85fc4115f8de)

**Comment by leeprince** [comment]
很细心👍，这个跟重复字段一样的问题了，原则上不支持这种表结构，你们公司有这种表结构？

**Comment by fengxueguang** [comment]
![image](https://github.com/leeprince/gormstruct/assets/7464025/454f3f96-1abf-42ac-b667-7b97b8236c05)
有，之前我是一个一个生成，周六我把我们1000多个表都生成了，结果好多错误。
其实这个不算是字段重复，这个算是生成的dao中的自动加s的问题

**Comment by fengxueguang** [comment]
一开始业务不一样，可能只创建了一个，后来业务发生了变化，就又创建了一个加s的字段，但是原字段如果直接删了，需要很多代码都删除，就保留了，只是不去用。
可以说不规范，但是真存在这种情况

**Comment by leeprince** [comment]
好的，看到你提交的merge request, merge
