### ISSUE TITLE
这个映射也有些问题

### ISSUE THREAD

**Issue by fengxueguang** [leeprince/gormstruct#8]
<img width="451" alt="image" src="https://github.com/leeprince/gormstruct/assets/7464025/506aed9b-4e26-49ef-99a3-7b5a0526a368">

比如我是测试环境所有的int都搞成int64了，
  smallint:            int64
  smallint(6): int64  这个没有写，结果导致smallint(6)就会生成一个int16吧，好像，不是64。
可实际上 smallint(6)这里面的6只是显示的而已，他实际占用的空间和smallint smallint(1)都是一样的。
所以针对smallint 应该只需要设计一个smallint就好了，不需要每一个都写一遍。
就算单独写了针对那个可以，但是不写，应该遵循的事smallint而不是找到默认的。

**Comment by leeprince** [comment]
代码model/common.go中是有兼容了，共有三种匹配模式

// getTypeName Type acquisition filtering.类型获取过滤
func getTypeName(sourceColumnName, sourceTypeName string, isNull bool) string {
  // 优先匹配自定义类型
  // 先精确匹配
  // 模糊正则匹配
